_wandb:
    value:
        cli_version: 0.18.0
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 7
                - 13
                - 23
                - 38
                - 55
            "4": 3.11.9
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
